blank_issues_enabled: false
contact_links:
  - name: Reglas de trabajo del equipo
    url: https://github.com/DylanSrz/FinancieraRiwi/blob/main/CONTRIBUTING.md
    about: Lee cómo creamos issues, ramas y pull requests.
